### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1024x2004 and 2000x1024)

### ISSUE THREAD

**Issue by xiaomaolxc** [Emad-COMBINE-lab/GRouNdGAN#10]
I'm sorry to bother you again, but after resolving the graphics card memory error I mentioned last time, I reduced the number and depth of genes. However, I encountered a new problem:
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1024x2004 and 2000x1024)
I encountered a similar problem before, but at that time my gene count was not correct. I adjusted the final screening gene count to fix this problem.
But this time, the number of genes I screened when creating the network was indeed 2000. Why is there a parameter of 2004 when training the network? I have checked my parameters and the results of network construction, and did not find any issues?
Afterwards, I consulted some information and identified the possible cause: certain genes could be both TF and Target, which resulted in the final total TF+Target being greater than 2000. How should I modify it? If you have any valuable suggestions, I would greatly appreciate it.
![image](https://github.com/Emad-COMBINE-lab/GRouNdGAN/assets/138417397/7e536497-15c7-4c93-bffb-22966264a048)
![image](https://github.com/Emad-COMBINE-lab/GRouNdGAN/assets/138417397/4ea6a4ce-7f53-4b45-90e3-dfad250e1750)

**Comment by xiaomaolxc** [comment]
![image](https://github.com/Emad-COMBINE-lab/GRouNdGAN/assets/138417397/24101765-9cdf-41af-80e0-309490938fbe)
And, I found that if I were to build the network in another way, I would choose 2000 genes, and the final number of selected genes would not be 2000, because some genes are neither TF nor Target.

**Comment by YazdanZ** [comment]
Hi, 

Can you provide the cfg file?
I suspect there is a mismatch between a parameter in the config and the data.

**Comment by YazdanZ** [comment]
I'm closing this issue as stale.
