### ISSUE TITLE
CUDA Out of Memory Error

### ISSUE THREAD

**Issue by abcdedcbaaa** [Emad-COMBINE-lab/GRouNdGAN#11]
Hello,

I was impressed by GRouNdGAN and wanted to try out the tutorial. However, I encountered some errors during the execution process and would appreciate your assistance in resolving them.

**- Following the tutorial steps, I entered the following commands in sequence.**

> python3.9 src/main.py --config configs/causal_gan.cfg --preprocess  
> python3.9 src/main.py --config configs/causal_gan.cfg --create_grn  
> python3.9 src/main.py --config configs/causal_gan.cfg --train  

**- I encountered the following error during the processing of the --train option.**

> done training step 199996  
> done training step 199997  
> done training step 199998  
> done training step 199999  
> /usr/local/lib/python3.9/site-packages/sklearn/manifold/_t_sne.py:780: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.  
>   warnings.warn(  
> /usr/local/lib/python3.9/site-packages/sklearn/manifold/_t_sne.py:790: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.  
>   warnings.warn(  
> done training step 200000  
> Traceback (most recent call last):  
>   File "/groundgan/src/main.py", line 44, in <module>  
>     fac.get_trainer()()  
>   File "/groundgan/src/factory.py", line 236, in <lambda>  
>     self.get_gan().train(  
>   File "/groundgan/src/gans/causal_gan.py", line 438, in train  
>     gen_loss = self._train_generator()  
>   File "/groundgan/src/gans/causal_gan.py", line 254, in _train_generator  
>     fake = self.gen(fake_noise)  
>   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl  
>     return forward_call(*input, **kwargs)  
>   File "/usr/local/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward  
>     return self.module(*inputs[0], **kwargs[0])  
>   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl  
>     return forward_call(*input, **kwargs)  
>   File "/groundgan/src/networks/masked_causal_generator.py", line 145, in forward  
>     gene_expression = self._generator(regulators)  
>   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl  
>     return forward_call(*input, **kwargs)  
>   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward  
>     input = module(input)  
>   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl  
>     return forward_call(*input, **kwargs)  
>   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/container.py", line 204, in forward  
>     input = module(input)  
>   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl  
>     return forward_call(*input, **kwargs)  
>   File "/groundgan/src/layers/masked_linear.py", line 123, in forward  
>     return MaskedLinearFunction.apply(input, self.weight, self.bias, self.mask)  
>   File "/groundgan/src/layers/masked_linear.py", line 22, in forward  
>     weight = weight * mask  
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.35 GiB (GPU 0; 23.64 GiB total capacity; 21.55 GiB already allocated; 901.50 MiB free; 21.59 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF  

**- To specify the checkpoint path, I checked the product file and found that two .pth files were generated in the results/GRouNdGAN_CC/checkpoints directory.**  

> /groundgan# ls -l results/GRouNdGAN  
> -rw-r--r-- 1 root root 3759 Jul 20 16:24 causal_gan.cfg  
>   
> /groundgan# ls -l results/GRouNdGAN_CC/  
> drwxr-xr-x 2 root root 4096 Jul 20 07:09 TSNE  
> drwxr-xr-x 8 root root 4096 Jul 20 04:37 TensorBoard  
> drwxr-xr-x 2 root root 4096 Jul 20 07:09 checkpoints  
>   
> /groundgan# ls -l results/GRouNdGAN_CC/checkpoints  
> -rw-r--r-- 1 root root 54449271 Jul 20 17:44 step_100000.pth  
> -rw-r--r-- 1 root root 54449271 Jul 20 19:04 step_200000.pth  
  
**- I then set the path to the checkpoint in configs/causal_gan.cfg as follows.**  
  
> [EXPERIMENT]  
> output directory = results/GRouNdGAN  
> device = cuda ; we will let the program choose what is available  
> checkpoint = results/GRouNdGAN_CC/checkpoints/step_200000.pth  ; set value to use a trained model  
  
**- I restarted with the --train option and encountered the following error.**  
  
> python3.9 src/main.py --config configs/causal_gan.cfg --train  
  
> Traceback (most recent call last):  
>   File "/groundgan/src/main.py", line 44, in <module>  
>     fac.get_trainer()()  
>   File "/groundgan/src/factory.py", line 236, in <lambda>  
>     self.get_gan().train(  
>   File "/groundgan/src/gans/causal_gan.py", line 399, in train  
>     self._load(checkpoint, mode="training")  
>   File "/groundgan/src/gans/causal_gan.py", line 177, in _load  
>     self.gen.load_state_dict(checkpoint["generator_state_dict"])  
>   File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict  
>     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(  
> RuntimeError: Error(s) in loading state_dict for CausalGenerator:  
>         Missing key(s) in state_dict: "_causal_controller._generator.0.0.weight", "_causal_controller._generator.0.0.bias", "_causal_controller._generator.0.1.weight", "_causal_controller._generator.0.1.bias", "_causal_controller._generator.0.1.running_mean", "_causal_controller._generator.0.1.running_var", "_causal_controller._generator.1.0.weight", "_causal_controller._generator.1.0.bias", "_causal_controller._generator.1.1.weight", "_causal_controller._generator.1.1.bias", "_causal_controller._generator.1.1.running_mean", "_causal_controller._generator.1.1.running_var", "_causal_controller._generator.2.0.weight", "_causal_controller._generator.2.0.bias", "_causal_controller._generator.2.1.weight", "_causal_controller._generator.2.1.bias", "_causal_controller._generator.2.1.running_mean", "_causal_controller._generator.2.1.running_var", "_causal_controller._generator.3.0.weight", "_causal_controller._generator.3.0.bias", "_generator.0.0.mask", "_generator.1.0.mask", "_generator.2.0.mask", "_generator.3.0.mask", "_generator.3.1.weight", "_generator.3.1.bias", "_generator.3.1.running_mean", "_generator.3.1.running_var", "_generator.4.0.mask", "_generator.4.0.weight", "_generator.4.0.bias", "_labeler.0.weight","_labeler.0.bias", "_labeler.1.weight", "_labeler.1.bias", "_labeler.1.running_mean", "_labeler.1.running_var", "_labeler.3.weight", "_labeler.3.bias", "_labeler.4.weight", "_labeler.4.bias", "_labeler.4.running_mean", "_labeler.4.running_var", "_labeler.6.weight", "_labeler.6.bias", "_labeler.7.weight", "_labeler.7.bias", "_labeler.7.running_mean", "_labeler.7.running_var", "_labeler.9.weight", "_labeler.9.bias".  
>         size mismatch for _generator.0.0.weight: copying a param with shape torch.Size([256, 128]) from checkpoint, the shape in current model is torch.Size([29984, 1000]).  
>         size mismatch for _generator.0.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.0.1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.0.1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.0.1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.0.1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.1.0.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([29984, 29984]).  
>         size mismatch for _generator.1.0.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.1.1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.1.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.1.1.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.1.1.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.2.0.weight: copying a param with shape torch.Size([1024, 512]) from checkpoint, the shape in current model is torch.Size([29984, 29984]).  
>         size mismatch for _generator.2.0.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape incurrent model is torch.Size([29984]).  
>         size mismatch for _generator.2.1.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.2.1.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape incurrent model is torch.Size([29984]).  
>         size mismatch for _generator.2.1.running_mean: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.2.1.running_var: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([29984]).  
>         size mismatch for _generator.3.0.weight: copying a param with shape torch.Size([1000, 1024]) from checkpoint, the shape in current model is torch.Size([29984, 29984]).  
>         size mismatch for _generator.3.0.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape incurrent model is torch.Size([29984]).  
  
I believe this issue arises because the program either does not have the correct checkpoint specified, or the specified checkpoint is not transitioning properly to the next stage, but I am not sure about the exact cause. I would appreciate any assistance you can provide regarding this matter.

Best Regards,  
Jay

**Comment by YazdanZ** [comment]
This issue is likely because you are running out of GPU memory. The log shows the the causal controller was successfully pre trained (for 200k steps) but it failed to initialize the second GAN. The easy solution is to use a GPU with higher vram (we used an A100 SXM4 40 GB). 

If you do not have access to a better GPU, you can check out the solutions I provided in #9 and #6 which make the model smaller and trainable on lower video memory.
