### ISSUE TITLE
Error check_values_indices_shape_match in create_grn

### ISSUE THREAD

**Issue by bazoogis** [Emad-COMBINE-lab/GRouNdGAN#8]
Hello,

I am trying to run the tutorial for GRouNdGAN, using the PBMC example, having kept the folder structure as is.

I have successfully run the preprocess command and the  train, test and validation files are created.

However, during the next step - create_grn, I get the following error:

File "/home/vzogop/GRouNdGAN/src/main.py", line 41, in <module>
    grn_creation.create_GRN(cfg_parser)
  File "/home/vzogop/GRouNdGAN/src/preprocessing/grn_creation.py", line 30, in create_GRN
    real_cells_df = pd.DataFrame(real_cells.X, columns=real_cells.var_names)
  File "/home/vzogop/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/frame.py", line 867, in __init__
    mgr = ndarray_to_mgr(
  File "/home/vzogop/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 336, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/home/vzogop/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 420, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (66579, 1), indices imply (66579, 1000)

As shown, I am using a python 3.9 environment created using miniconda to run GRouNdGAN.

Best Regards,
Bill

**Comment by YazdanZ** [comment]
Hi, 

can you provide us with the .cfg file that you used? Did you use the provided one without any modifications?

**Comment by lryup** [comment]
I have the same mistake.

**Comment by bazoogis** [comment]
> Hi,
> 
> can you provide us with the .cfg file that you used? Did you use the provided one without any modifications?
> 
> The problem seems to be the number of genes in the GEX matrix (1 instead of 1000).

[causal_gan.txt](https://github.com/user-attachments/files/16039843/causal_gan.txt)

It's the same .cfg file as was provided, I only made slight folder modifications. Nevertheless, I attach it here.



> I have the same mistake.
> 
> you need change code:
> 
> real_cells_df = pd.DataFrame.sparse.from_spmatrix(real_cells.X, index=real_cells.obs_names, columns=real_cells.var_names)

Thanks, this seems to have gotten over this issue, although I'm getting a different error now: 

parsing input
creating dask graph
shutting down client and local cluster
finished
Traceback (most recent call last):
  File "/home/vzogop/GRouNdGAN/src/main.py", line 41, in <module>
    grn_creation.create_GRN(cfg_parser)
  File "/home/vzogop/GRouNdGAN/src/preprocessing/grn_creation.py", line 35, in create_GRN
    real_grn = grnboost2(real_cells_df, tf_names=TFs, verbose=True, seed=1)
  File "/home/vzogop/miniconda3/envs/myenv/lib/python3.9/site-packages/arboreto/algo.py", line 39, in grnboost2
    return diy(expression_data=expression_data, regressor_type='GBM', regressor_kwargs=SGBM_KWARGS,
  File "/home/vzogop/miniconda3/envs/myenv/lib/python3.9/site-packages/arboreto/algo.py", line 120, in diy
    graph = create_graph(expression_matrix,
  File "/home/vzogop/miniconda3/envs/myenv/lib/python3.9/site-packages/arboreto/core.py", line 450, in create_graph
    all_meta_df = from_delayed(delayed_meta_dfs, meta=_META_SCHEMA)
  File "/home/vzogop/miniconda3/envs/myenv/lib/python3.9/site-packages/dask_expr/io/_delayed.py", line 101, in from_delayed
    raise TypeError("Must supply at least one delayed object")
TypeError: Must supply at least one delayed object


Best Regards,
Bill

**Comment by lryup** [comment]
I am not modifying any folders, and .cfg files.
After the correction, 
```
    TFs = list(set(TFs).intersection(gene_names))
    # 李荣远修正错误
    # preparing GRNBoost2's input
    real_cells_df = pd.DataFrame.sparse.from_spmatrix(real_cells.X, index=real_cells.obs_names, columns=real_cells.var_names)
    # real_cells_df = pd.DataFrame(real_cells.X, index=real_cells.obs_names,columns=real_cells.var_names)
    # we can optionally pass a list of TFs to GRNBoost2
    print(f"Using {len(TFs)} TFs for GRN inference.")
    real_grn = grnboost2(real_cells_df, tf_names=TFs, verbose=True, seed=1)
    real_grn.to_csv(cfg.get("GRN Preparation", "Inferred GRN"))
```

run the following command.
$ python src/main.py --config configs/causal_gan.cfg --create_grn

The results are the same as the authors.

TFs                          63
Targets                     937
Genes                      1000
Possible Edges            59031
Imposed Edges             14055
GRN density Edges      0.238095

**Comment by YazdanZ** [comment]
I'm unable to reproduce the error on my local installation of GRouNdGAN. 
Can you provide me with the package versions you have installed? 

`pip freeze > requirements.txt`

I'll see if I can reproduce the error with your package versions

**Comment by bazoogis** [comment]
I did a fresh installation of both the 3.9 python environment and the requirements and it seems to be working now!

Just for information, I attach my pip packages version.

[requirements_1.txt](https://github.com/user-attachments/files/16390453/requirements_1.txt)

**Comment by YazdanZ** [comment]
I found the source of the problem. This only happens when the package versions aren't right for some reason. 
It's because the `adata.X` is saved as a sparse matrix. You can take the .h5ad files saved in the `data/processed/` directory and convert the `adata.X` to a dense matrix. 

```
import scanpy as sc
adata = sc.read_h5ad('data/processed/PBMC/PBMC68k_train.h5ad')
adata.X = adata.X.toarray()
sc.write_h5ad('data/processed/PBMC/PBMC68k_train.h5ad') # overwrite the preprocessed file
```

Repeat for PBMC68k_validation.h5ad and PBMC68k_validation.h5ad
